Q1

In [1]:
import scipy.io as sio
import numpy as np

x = np.array([[1, 2, 3,4], 
              [5, 6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

sio.savemat('test.mat', {"f":x})
data = sio.loadmat('test.mat')
print(data)

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Wed Jun  9 08:05:51 2021', '__version__': '1.0', '__globals__': [], 'f': array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])}


Q2

In [2]:
from scipy.special import cbrt

res = cbrt([27, 64, 891])
print(res)

[3.         4.         9.62260299]


Q3

In [3]:
from scipy import linalg
import numpy as np

x = np.array([[4,5], 
              [3,2]])
y = linalg.det(x)

z = linalg.inv(x)

print(y)

print("\n")

print(z)

-7.0


[[-0.28571429  0.71428571]
 [ 0.42857143 -0.57142857]]


Q4

In [4]:
import scipy.linalg as la
import numpy as np


x = np.array([[5,4], 
              [6,3]])

eigvals, eigvecs = la.eig(x)
print(eigvals)
print("\n")
print(eigvecs)

[ 9.+0.j -1.+0.j]


[[ 0.70710678 -0.5547002 ]
 [ 0.70710678  0.83205029]]


Q5

In [5]:
from scipy.sparse import diags
from scipy import sparse
diagonals = [[1, 2, 3, 4], [1, 2, 3], [1, 2]]

A = diags(diagonals, [0, -1, 2]).toarray()
B = sparse.eye(3).toarray()

print(A)
print("\n")
print(B)

sparse.isspmatrix(A)
sparse.isspmatrix(B)

[[1. 0. 1. 0.]
 [1. 2. 0. 2.]
 [0. 2. 3. 0.]
 [0. 0. 3. 4.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


False